services:
  subsnap:
    image: ghcr.io/rs-jensen/subsnap:latest  
    restart: always
    volumes:
      - ./data:/data
      - /path/to/movies:/media/movies      
      - /path/to/series:/media/series       
    environment:
      - MEDIA_ROOT=/media
      - DB_PATH=/data/subsnap.db
      - SUBSNAP_BIN=/app/subsnap