services:
  subsnap:
    container_name: subsnap
    image: ghcr.io/rs-jensen/subsnap:latest
    restart: always
    ulimits:
      core: 0
    tmpfs:
      - /tmp
    volumes:
      - ./data:/data
      - /mnt/media:/media
    environment:
      - MEDIA_ROOT=/media
      - DB_PATH=/data/subsnap.db
      - SUBSNAP_BIN=/app/subsnap